# CodeRabbit Configuration
# See: https://docs.coderabbit.ai/guides/configure-coderabbit

language: ja-JP

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto

tone_instructions: |
  - コードレビューは日本語で実施
  - 建設的で丁寧なフィードバックを心がける
  - セキュリティやパフォーマンスの問題は明確に指摘
  - ベストプラクティスに基づいた改善提案を行う

early_access: false
enable_free_tier: true
